### ISSUE TITLE
Skycons with different colors in typescript

### ISSUE THREAD

**Issue by Hercules-Macedo** [andipaetzold/skycons-ts#17]
Hi, i use your skycons-ts, so i found in github another skycon that use multiple colours in icons, for example cloud in gray and rain in blue in the same canvas, but this version is only in js, can you make a alternative version, as same as https://github.com/maxdow/skycons, but in TS?

**Comment by andipaetzold** [comment]
Hey, great to hear that you are using the library!

Adding some more color to the icons sounds interesting. It doesn't seem to be very difficult to implement, so I'll have a look at it. :)

**Comment by andipaetzold** [comment]
Just released as 0.1.0
