### ISSUE TITLE
if more icons could be included by this project?

### ISSUE THREAD

**Issue by HerbertHe** [andipaetzold/skycons-ts#36]
the project forked and committed by [maxdow/skycons](https://github.com/maxdow/skycons) includes more icons

**Comment by andipaetzold** [comment]
I just release a [new version](https://github.com/andipaetzold/skycons-ts/releases/tag/v0.2.0) with many more icons and icon combinations.

**Comment by HerbertHe** [comment]
🆗but I had already packaged by myself 😄
